### PR TITLE
Issue #419: update 2.1.x maintenance branch to 2.1.2

### PR DESCRIPTION
**Pull request by elder4p**
Setup up 2.1.2 builds on streams/v2.1.x-maintenance branch.

### CODE REVIEW

**Comment by J17359** [comment]
Is there no automated build associated with this PR? It would be nice to see the artifacts produced with the new versions as a double check that nothing breaks :)

**Comment by elder4p** [comment]
> Is there no automated build associated with this PR? It would be nice to see the artifacts produced with the new versions as a double check that nothing breaks :)

@17359: Just checked. There isn't. I'll update the rules to include the maintenance branches.

**Comment by elder4p** [comment]
@J17359 : There we go. Build has started. Once you've confirmed all the artifacts are OK, I'll make a similar change on the 'papyrus' branch so that this behaviour will carry forward when we next create a maintenance branch.

**Comment by elder4p** [comment]
@J17359 : Also adding you as an official reviewer of this pull request. Once you are satisfied, please give your +1. Thanks.

**Review by J17359 — APPROVED** [review]
Looks great! Build logs showed no occurrences of old `2.1.1` version and artifacts produced with new `2.1.2` version.

**Comment by elder4p** [comment]
@J17359 : I notice the papyrus 4.4.0 patch feature is still 2.1.0. Do we care? There has, of course, been no change there. Have you checked the RPM? I know I changed the version, but I do not trust myself on anything RPM.

**Comment by J17359** [comment]
> @J17359 : I notice the papyrus 4.4.0 patch feature is still 2.1.0. Do we care? There has, of course, been no change there. Have you checked the RPM? I know I changed the version, but I do not trust myself on anything RPM.

Yes the RPM looks good!

As for the papyrus patch, I don't have a personal preference really. If it's not too much work, maybe roll it to `2.1.2` for consistency's sake? We must have missed rolling it to `2.1.1` when we did the initial version bump on that streams branch.

**Review by ysroh — APPROVED** [review]
Looks good

**Comment by elder4p** [comment]
@J17359 , @ysroh : I have updated the pull papyrus patch version to 2.1.2. Build runs successfully, so I will merge.

**Pull request merged**
