### PR TITLE
Papyrus Patch addressing #376

### PR DESCRIPTION
**Pull request by elder4p**
Patch Papyrus plug-in org.eclipse.papyrus.uml.properties bug. Fix includes:

* patched plug-in
* a patch feature + individually installable update site (for use with manually installed CX)
* updated papyrus-cx-axioma eclipse 'product' that includes the patch already installed.

### CODE REVIEW

**Review by ysroh — APPROVED** [review]
Looks good, thanks

**Comment by J17359** [comment]
@elder4p @ysroh @eposse 

After this PR was merged, our internal build of your `papyrus` branch started failing. I noticed y'all [added a section to your linux_build.yml file](https://github.com/ZeligsoftDev/CX4CBDDS/blob/c42682242f26174ac77041a69962decb25a83473/.github/workflows/linux_build.yml#L66-L69) to build that papyrus patch prior to building the rest of CX. However, when we run this internally, we get the following Maven error:
image

I've also attached the full build failure log output. I'm running that command inside the `papyrus-patch/v4.8.0` folder as shown in your `linux_build.yml` file linked above.

[test.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/9131988/test.txt)

CC @j26151

**Comment by J17359** [comment]
For what it's worth, I'm getting that same error on the previous build call too (running maven at the top of the repo).

**Comment by elder4p** [comment]
@J17359 : Apologies. Because of limitations in Maven/Tycho, the 'patch' is now built separately with a separate maven invocation. Your build script must now include:

```
# assuming your starting in your build directory
pushd papyrus-patch/v4.8.0
../../mvnw clean verify
popd
# existing build steps
```

I see you are including extra arguments on the maven command line. You may need to include those the above command, too.

You can see the extra build step in our GitHub action [here](https://github.com/ZeligsoftDev/CX4CBDDS/blob/70f437f7f2e38a85a5c704637bbdc4073ae6221c/.github/workflows/linux_build.yml#L66).

**Comment by J17359** [comment]
@elder4p I saw all those things and included the extra args on the cmd line as I was doing before. The failure is happening in the papyrus-patch/v4.8.0 build AND in the root build.
image

It looks like we're getting some sort of Java version mismatch on the Tycho class that gets pulled in. We have Java 11 installed and set as the default in /etc/alternatives.

**Comment by elder4p** [comment]
@J17359 : I notice you are using `mvn` instead of our `mvnw` command. The later is a 'Maven wrapper' that allows us to specify the maven version we use so that we get consistent results across all builds. The wrapper will download the 'right' version (3.6.3) to a build-local directory; it will not change your default installation.

Try using `./mvnw`.

**Comment by J17359** [comment]
@elder4p `./mvnw` takes no argument to a proxy file so we can't use it. We aren't allowed to just reach out to the internet and grab that latest Maven. We could do so through a proxy file (as you can see we do when calling our mvn command above). 

To show you what happens when I run with that `/.mvnw` command:
image

**Comment by elder4p** [comment]
@J17359 : aw, this makes things more complicated. First, my theory: `mvn` it using Java 8, but the latest Tycho plug-ins require Java 11. Try the following and note the Java version reported:

```mvn --version```

We introduced `mvnw` because we encountered several build failures introduced by updates to Maven. The problem comes down to getting a correctly configured Maven 3.6.3 (our currently specified version) installed on your build machine, and ensuring that it uses Java 11.

One mystery: nothing has changed in this regard. The Tycho plug-in you are failing to load has always been a Java 11 (55.0) versioned plug-in (as far as I know).

**Comment by elder4p** [comment]
@J17359 : it seems Maven Wrapper has evolved since we first adopted it, including moving directly into the Maven project. I see an [old ticket](https://github.com/takari/maven-wrapper/issues/58) (2015-2019) about this issue, but it was resolved with a work around, not a solution. I'm looking at the [new Maven Wrapper home](https://maven.apache.org/wrapper/) to see whether a newer version resolves this.

**Comment by J17359** [comment]
@elder4p I found [this stackoverflow](https://stackoverflow.com/a/44500269/2108647) that shows I can `export MAVEN_OPTS=...` to set my proxy. That got me past the SSL error but I'm back at the Java error. Let me reset my system as I've been changing a lot of things at once and want to make sure I'm back at a clean slate. I'll keep you posted.

**Pull request merged**
