### PR TITLE
Issue #193: Papyrus rpm deps

### PR DESCRIPTION
**Pull request by eposse**
This updates the rpm spec file and the category.xml for the axcioma update site to include all required dependencies.

### CODE REVIEW

**Comment by J17359** [comment]
To make this easier for future updates, you could define the list of installation units once at the top of the file and then pass the list in four times instead of having that massive list copy/pasted 4 times. Up to you!

    # Define this above the preamble (i.e. above the Name:, Version:, Release: lines)
    %define feature_groups "org.eclipse.cdt.feature.group, \
        com.zeligsoft.base_feature.feature.group , \
        com.zeligsoft.cx_feature.feature.group , \
        org.eclipse.papyrus.compare.feature.feature.group" \
        <all the other feature groups from the list>
        ...
        
    ...

    # Then, in you spec file scriptlets, use that feature groups list variable
    %pre
    axciomaInstalledFeature=$(/opt/Papyrus/papyrus -application org.eclipse.equinox.p2.director -listInstalledRoots -nosplash | grep com.zeligsoft.domain.ngc.ccm.axcioma_feature.feature.group)
    atcdInstalledFeature=$(/opt/Papyrus/papyrus -application org.eclipse.equinox.p2.director -listInstalledRoots -nosplash | grep com.zeligsoft.domain.ngc.ccm_feature.feature.group)

    if [[ ${axciomaInstalledFeature} != "" ]]; then 		# axcioma is already installed
    /opt/Papyrus/papyrus \
       -application org.eclipse.equinox.p2.director \
       -nosplash \
       -uninstallIU %{feature_groups} \
       -vmargs \
       -Xms512m \
       -Xmx1024m \
       -XX:+UseParallelGC \
       -XX:PermSize=256M \
       -XX:MaxPermSize=512M
    elif [[ ${atcdInstalledFeature} != "" ]]; then 		# atcd is already installed
    /opt/Papyrus/papyrus \
       -application org.eclipse.equinox.p2.director \
       -nosplash \
       -uninstallIU %{feature_groups} \
       -vmargs \
       -Xms512m \
       -Xmx1024m \
       -XX:+UseParallelGC \
       -XX:PermSize=256M \
       -XX:MaxPermSize=512M
    fi

    %post
    # Get timestamp of CX zip file
    timestamp=$(echo /opt/cx-axcioma/*.zip | sed -rn 's/.*\.v([0-9]*)\.zip/\1/p')
    /opt/Papyrus/papyrus \
       -application org.eclipse.equinox.p2.director \
       -nosplash \
       -repository \
       jar:file:/opt/cx-axcioma/dds4ccm_axcioma_%{ver}.v${timestamp}.zip\!/ \
       -installIU %{feature_groups}


    %postun
    if [ $1 == 0 ] ; then					# this is an uninstallation, not an upgrade
    /opt/Papyrus/papyrus \
       -application org.eclipse.equinox.p2.director \
       -nosplash \
       -uninstallIU %{feature_groups} \
       -vmargs \
       -Xms512m \
       -Xmx1024m \
       -XX:+UseParallelGC \
       -XX:PermSize=256M \
       -XX:MaxPermSize=512M
    fi

**Comment by eposse** [comment]
Hi @J17359 That's a good idea. I just copied and pasted due to my lack of familiarity with RPM specs. I'll make the change.

**Comment by J17359** [comment]
@eposse - The feature groups must be comma separated and the $feature_group references need to be %feature_group. Spec files use the % for internal variables and the $ for environment variables.

**Comment by eposse** [comment]
@J17359 I've pushed an updated version of the spec file doing the refactoring that you suggested, but it fails to install with an error: "Option -installIU requires an argument." 

Can you take a look at the updated spec file to see what I'm doing wrong?

Thanks.

**Comment by J17359** [comment]
> @J17359 I've pushed an updated version of the spec file doing the refactoring that you suggested, but it fails to install with an error: "Option -installIU requires an argument."
> 
> Can you take a look at the updated spec file to see what I'm doing wrong?
> 
> Thanks.

See my comment above yours: https://github.com/ZeligsoftDev/CX4CBDDS/pull/200#issuecomment-718131255

**Comment by eposse** [comment]
Thanks. I'll fix it and push it.

**Pull request merged**
